### ISSUE TITLE
Nav Drawer: Fix cover photo width

### ISSUE THREAD

**Issue by prempalsingh** [teamOSC/studdd.in_android#6]

**Comment by omerjerk** [comment]
And also add border around profile photo.

**Comment by yogeshbalan** [comment]
ok

**Comment by omerjerk** [comment]
@yogeshbalan  Also replace the default placeholder image with something more suitable.

**Comment by prempalsingh** [comment]
@yogeshbalan This has been fixed now, right?

**Comment by omerjerk** [comment]
yes.

**Comment by yogeshbalan** [comment]
yes @prempalsingh
